---
- hosts: "*"
  become: yes
  become_user: root
  # Required on first run:
  # user: root
  # After first run:
  user: james
  vars_files:
    - vars/secret_vars.yml
    - vars/shared_vars.yml
  vars:
    zookeeper_pkg: http://mirrors.ukfast.co.uk/sites/ftp.apache.org/zookeeper/zookeeper-3.4.13/zookeeper-3.4.13.tar.gz
    zookeeper_dir: /opt/zookeeper-3.4.13
    zookeeper_data_dir: /var/lib/zookeeper
    zookeeper_log_dir: /var/log/zookeeper
  roles:
    - base
    - zookeeper
