- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: install all locales
  apt:
    name: locales-all

- name: rngd requires entropy sources which the VM doesn't have
  apt:
    state: absent
    name: rng-tools5

- name: don't create confusing menu.lst that isn't used
  apt:
    state: absent
    name: grub-legacy-ec2

- name: give grub a timeout so we can boot through recovery mode to avoid entropy issues
  copy:
    src: 50-cloudimg-settings.cfg
    dest: /etc/default/grub.d/50-cloudimg-settings.cfg
  register: grub_settings

- name: update grub config with timeout
  command: /usr/sbin/update-grub
  when: grub_settings.changed

- name: create the james group
  group:
    name: james
    gid: 10001

- name: create the james user
  user:
    name: james
    uid: 10001
    group: 10001
    groups: sudo
    shell: /bin/bash
    password: "{{ james_password }}"

- name: add james' SSH key
  authorized_key:
    user: james
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID3Eru8kx+r3voeopwcM5cET36rVNYvKEeplIbg+Iw5j james@nice-goat-bro"

- name: disable swap
  sysctl:
    name: vm.swappiness
    value: 0

- name: install Java
  apt:
    name: openjdk-11-jre-headless
    update_cache: yes

- name: setup ZK hosts file entries
  lineinfile:
    path: /etc/hosts
    line: "{{ item.value.ip }} {{ item.key }}"
  loop: "{{ zookeeper_hosts|dict2items }}"

- name: setup Kafka hosts file entries
  lineinfile:
    path: /etc/hosts
    line: "{{ item.value.ip }} {{ item.key }}"
  loop: "{{ kafka_hosts|dict2items }}"
